name: build

on:
  push:
    branches: [main, new-yaml-controls]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [18.x, 20.x, 22.x]
        node-version: [20.x]
    permissions:
      contents: write
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: Build
        run: |
          npm install
          npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Add dist files
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: './dist --force'
